---
- hosts: webservers
  become: yes
  tasks:
  - name: install webserver on ubuntu nodes
    apt:
     name: "{{webserverpackforubuntu}}"
     state: present
    when: ansible_os_family =="Debian"

  - name: start webserver on ubuntu nodes 
    service:
     name: "{{webserverpackforubuntu}}"
     state: started
    when: ansible_os_family =="Debian"

  - name: install webserver on redhat nodes
    yum:
     name: "{{webserverpackforredhat}}"
     state: present
    when: ansible_os_family =="RedHat"

  - name: start webserver on redhat nodes 
    service:
     name: "{{webserverpackforredhat}}"
     state: started
    when: ansible_os_family =="RedHat"
 
  
